checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12
                variables:
                    name: 'REBUILD::0'

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage-0:
            environment:
                php: 7.4.12
                variables:
                    name: 'REBUILD::0'

            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover

        tests-and-coverage-1:
            environment:
                php: 7.4.12
                variables:
                    name: 'REBUILD::1'

            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 2
                        coverage:
                            file: coverage.xml
                            format: php-clover
